# Generated by Django 4.2 on 2023-05-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_remove_channel_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
    ]
