# Generated by Django 4.2 on 2023-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_alter_channel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
