# Generated by Django 4.2 on 2023-05-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_alter_playlist_videos_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.video'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tube.channel'),
        ),
    ]
