# Generated by Django 4.2 on 2023-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_alter_channel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
