# Generated by Django 4.1.9 on 2023-05-15 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_dislikedvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlists', models.ManyToManyField(blank=True, related_name='saved_playlists', to='tube.playlist')),
                ('viewer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
    ]
