# Generated by Django 4.2 on 2023-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_commentreply_channel_alter_commentreply_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, to='tube.video'),
        ),
    ]
