# Generated by Django 4.2 on 2023-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_video_private_video_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
