# Generated by Django 4.1.9 on 2023-05-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_savedplaylists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikedvideos',
            name='viewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer'),
        ),
        migrations.AlterField(
            model_name='likedvideos',
            name='viewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer'),
        ),
        migrations.AlterField(
            model_name='savedplaylists',
            name='viewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer'),
        ),
    ]
