# Generated by Django 4.2 on 2023-05-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_alter_playlist_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
