# Generated by Django 4.2 on 2023-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_playlist_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='website_official',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
