# Generated by Django 4.1.9 on 2023-05-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_alter_dislikedvideos_viewer_alter_likedvideos_viewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('videos', models.ManyToManyField(blank=True, related_name='history', to='tube.video')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
    ]
