# Generated by Django 4.2 on 2023-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_channel_website_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
