# Generated by Django 4.2 on 2023-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_remove_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
