# Generated by Django 4.1.9 on 2023-05-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikedvideos',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='history',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='likedvideos',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='created_on',
        ),
    ]
