# Generated by Django 4.2 on 2023-05-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
