# Generated by Django 4.1.9 on 2023-05-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_remove_dislikedvideos_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to='tube.channel')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
    ]
