# Generated by Django 4.2 on 2023-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_alter_channel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
