# Generated by Django 4.2 on 2023-05-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_alter_video_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('videos', models.ManyToManyField(blank=True, related_name='watch_later', to='tube.video')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
    ]
