# Generated by Django 4.2 on 2023-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0011_watchlater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='public',
        ),
    ]
