# Generated by Django 4.2 on 2023-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_remove_watchlater_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
