# Generated by Django 4.2 on 2023-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_channel_subscribers_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='gender',
            field=models.CharField(choices=[('select', 'SELECT'), ('male', 'MALE'), ('female', 'FEMALE'), ('OTHER', 'OTHER'), ('prefer not to say', 'PREFER NOT TO SAY')], max_length=30, null=True),
        ),
    ]
