# Generated by Django 4.1.9 on 2023-05-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0013_rename_views_history_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='view',
            new_name='views',
        ),
    ]
