# Generated by Django 4.1.9 on 2023-05-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0014_rename_view_history_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoview',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='viewer',
        ),
        migrations.AddField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tube.video'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tube.viewer'),
        ),
    ]
