# Generated by Django 4.1.9 on 2023-05-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0015_remove_videoview_video_remove_videoview_viewer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoview',
            old_name='viewed',
            new_name='viewed_on',
        ),
    ]
