# Generated by Django 4.1.9 on 2023-05-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0016_rename_viewed_videoview_viewed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.video'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer'),
        ),
    ]
