# Generated by Django 4.1.9 on 2023-05-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0017_alter_videoview_video_alter_videoview_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.channel'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.channel'),
        ),
    ]
