# Generated by Django 4.1.9 on 2023-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0018_alter_comment_channel_alter_commentreply_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_active',
            field=models.BooleanField(default=True),
        ),
    ]
