# Generated by Django 4.1.9 on 2023-05-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0019_channel_channel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedCommentsReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_replies', models.ManyToManyField(blank=True, related_name='liked_comment_replies', to='tube.commentreply')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='LikedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ManyToManyField(blank=True, related_name='liked_comments', to='tube.comment')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='DisLikedCommentsReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_replies', models.ManyToManyField(blank=True, related_name='disliked_comment_replies', to='tube.commentreply')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='DisLikedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ManyToManyField(blank=True, related_name='disliked_comments', to='tube.comment')),
                ('viewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.viewer')),
            ],
        ),
    ]
