# Generated by Django 4.1.9 on 2023-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0020_likedcommentsreplies_likedcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.URLField(blank=True, max_length=450, null=True, unique=True),
        ),
    ]
