# Generated by Django 4.1.9 on 2023-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0022_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
