# Generated by Django 4.1.9 on 2023-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0024_viewer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='paid_viewers',
            field=models.ManyToManyField(blank=True, related_name='paid_viewers', to='tube.viewer'),
        ),
    ]
