# Generated by Django 4.1.9 on 2023-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0027_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
