# Generated by Django 4.1.9 on 2023-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0034_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='viewer_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
