# Generated by Django 4.1.9 on 2023-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='videos',
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.DateTimeField(auto_now_add=True)),
                ('video', models.ManyToManyField(blank=True, related_name='view_video', to='tube.video')),
                ('viewer', models.ManyToManyField(blank=True, related_name='view_viewer', to='tube.viewer')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='history', to='tube.videoview'),
        ),
    ]
