# Generated by Django 4.1.9 on 2023-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0011_remove_history_videos_videoview_history_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='view',
        ),
        migrations.AddField(
            model_name='history',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='history', to='tube.videoview'),
        ),
    ]
