# Generated by Django 4.1.9 on 2023-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0025_video_paid_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
