# Generated by Django 4.1.9 on 2023-08-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0036_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commmented_on',
            new_name='commented_on',
        ),
    ]
