# Generated by Django 4.1.9 on 2023-08-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0037_rename_commmented_on_comment_commented_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='user',
            new_name='viewer',
        ),
    ]
